version: '3.8'

services:
  backend:
    container_name: symfony_app
    build:
      context: ./symfony
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SYMFONY_ALLOW_ALL_IPS=1
    volumes:
      - ./symfony:/var/www/symfony
    working_dir: /var/www/symfony
    command: symfony server:start --no-tls --allow-all-ip
    networks:
      - app_network

  frontend:
    container_name: react_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
