nelmio_api_doc:
    documentation:
        info:
            title: "API Dokumentacja"
            description: "Opis dostępnych endpointów"
            version: "1.0.0"
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api
