api_home:
    path: /api/home
    controller: App\Controller\ApiController::home
    methods: GET
api_users:
    path: /api/users
    controller: App\Controller\ApiController::getUsers
    methods: GET
api_user:
    path: /api/user/{nick}
    controller: App\Controller\ApiController::getUserByNick
    methods: GET
api_posts:
    path: /api/posts/{id}
    controller: App\Controller\ApiController::getPostById
    methods: GET
api_userId:
    path: /api/userId/{id}
    controller: App\Controller\ApiController::getUserById
    methods: GET


