api_home:
    path: /api/home
    controller: App\Controller\ApiController::home
    methods: GET
api_users:
    path: /api/users
    controller: App\Controller\ApiController::getUsers
    methods: GET
api_user:
    path: /api/user/{nick}
    controller: App\Controller\ApiController::getUserByNick
    methods: GET
api_posts:
    path: /api/posts
    controller: App\Controller\ApiController::getPosts
    methods: GET
api_postId:
    path: /api/post/{id}
    controller: App\Controller\ApiController::getPostById
    methods: GET
api_userId:
    path: /api/userId/{id}
    controller: App\Controller\ApiController::getUserById
    methods: GET
api_createUser:
    path: /api/createUser
    controller: App\Controller\ApiController::createUser
    methods: POST
register:
    path: /api/register
    controller: App\Controller\ApiController::register
    methods: POST
likePost:
    path: /api/likePost
    controller: App\Controller\ApiController::likePost
    methods: POST
notifications:
    path: /api/notifications
    controller: App\Controller\ApiController::notifications
    methods: GET
login:
    path: /api/login
    #controller: App\Controller\ApiController::login
    methods: POST
